### ISSUE TITLE
DLM to core migration job follow-up work

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot-app-device-lifecycle-mgmt#398]
### PR #400
- [ ] Add foreign keys from Software, SoftwareImage, ContactLCM to core models to document the migration.
- [ ] Update the 3.0 migrations for DLM models that have Foreign keys to Software, rename the existing foreign key to software_old, add a new nullable foreign key to the core model. Update the UI and serializer to make the new nullable foreign key required.

### To be moved into separate issues

```[tasklist]
### Tasks
- [ ] https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/issues/402
- [ ] https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/issues/403
- [ ] https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/issues/404
- [ ] https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/issues/405
- [ ] https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/issues/406
```

**Comment by gsnider2195** [comment]
Before marking this as ready I need to ensure that the existing constraints/indexes get deleted when a table is dropped. Both mysql and postgres

**Comment by gsnider2195** [comment]
Confirmed the mysql constraints are dropped when the table is dropped:

```
gary@gary-work:~/github/nautobot/nautobot-app-device-lifecycle-mgmt (u/gas-398-dlm-to-core-migrations)$ diff -u mysql_constraints_before.txt mysql_constraints_after.txt 
--- mysql_constraints_before.txt        2025-01-13 16:42:43.052351023 -0800
+++ mysql_constraints_after.txt 2025-01-13 16:44:26.281598894 -0800
@@ -12,7 +12,6 @@
 | nautobot_device_life_contract_id_bc2cb084_fk_nautobot_          | nautobot_device_lifecycle_mgmt_contactlcm                        | FOREIGN KEY     |
 | nautobot_device_life_contractlcm_id_41661570_fk_nautobot_       | nautobot_device_lifecycle_mgmt_contractlcm_devices               | FOREIGN KEY     |
 | nautobot_device_life_cve_id_ab5e9c3a_fk_nautobot_               | nautobot_device_lifecycle_mgmt_vulnerabilitylcm                  | FOREIGN KEY     |
-| nautobot_device_life_cvelcm_id_4b8dbe39_fk_nautobot_            | nautobot_device_lifecycle_mgmt_cvelcm_old_affected_softwares     | FOREIGN KEY     |
 | nautobot_device_life_cvelcm_id_6e6d105b_fk_nautobot_            | nautobot_device_lifecycle_mgmt_cvelcm_affected_softwares         | FOREIGN KEY     |
 | nautobot_device_life_device_id_0a2651e1_fk_dcim_devi            | nautobot_device_lifecycle_mgmt_devicehardwarenoticeresult        | FOREIGN KEY     |
 | nautobot_device_life_device_id_0a4868ea_fk_dcim_devi            | nautobot_device_lifecycle_mgmt_validatedsoftwarelcm_devices      | FOREIGN KEY     |
@@ -47,7 +46,6 @@
 | nautobot_device_life_softwareimagelcm_id_bb8c26b2_fk_nautobot_  | nautobot_device_lifecycle_mgmt_softwareimagelcm_object_tags      | FOREIGN KEY     |
 | nautobot_device_life_softwareimagelcm_id_bc13369f_fk_nautobot_  | nautobot_device_lifecycle_mgmt_softwareimagelcm_device_types     | FOREIGN KEY     |
 | nautobot_device_life_softwareimagelcm_id_c994dff5_fk_nautobot_  | nautobot_device_lifecycle_mgmt_softwareimagelcm_inventory_items  | FOREIGN KEY     |
-| nautobot_device_life_softwarelcm_id_fb165fdc_fk_nautobot_       | nautobot_device_lifecycle_mgmt_cvelcm_old_affected_softwares     | FOREIGN KEY     |
 | nautobot_device_life_softwareversion_id_4b1a6461_fk_dcim_soft   | nautobot_device_lifecycle_mgmt_cvelcm_affected_softwares         | FOREIGN KEY     |
 | nautobot_device_life_status_id_d0f514c9_fk_extras_st            | nautobot_device_lifecycle_mgmt_vulnerabilitylcm                  | FOREIGN KEY     |
 | nautobot_device_life_status_id_fe6cdfe8_fk_extras_st            | nautobot_device_lifecycle_mgmt_cvelcm                            | FOREIGN KEY     |
@@ -78,14 +76,12 @@
 | nautobot_device_lifecycl_validatedsoftwarelcm_id__4aaa0872_uniq | nautobot_device_lifecycle_mgmt_validatedsoftwarelcm_device_types | UNIQUE          |
 | nautobot_device_lifecycl_validatedsoftwarelcm_id__bfe2bccf_uniq | nautobot_device_lifecycle_mgmt_validatedsoftwarelcm_device_roles | UNIQUE          |
 | nautobot_device_lifecycl_validatedsoftwarelcm_id__d1c31dd6_uniq | nautobot_device_lifecycle_mgmt_validatedsoftwarelcm_inventorf70b | UNIQUE          |
-| nautobot_device_lifecycle_m_cvelcm_id_softwarelcm_id_3122703f   | nautobot_device_lifecycle_mgmt_cvelcm_old_affected_softwares     | UNIQUE          |
 | nautobot_device_lifecycle_mgmt_contactlcm_chk_1                 | nautobot_device_lifecycle_mgmt_contactlcm                        | CHECK           |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_contactlcm                        | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_contractlcm                       | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_contractlcm_devices               | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_cvelcm                            | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_cvelcm_affected_softwares         | PRIMARY KEY     |
-| PRIMARY                                                         | nautobot_device_lifecycle_mgmt_cvelcm_old_affected_softwares     | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_devicehardwarenoticeresult        | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_devicesoftwarevalidationresulaace | PRIMARY KEY     |
 | PRIMARY                                                         | nautobot_device_lifecycle_mgmt_devicesoftwarevalidationresult    | PRIMARY KEY     |
@@ -108,3 +104,4 @@
 | unique_device_type                                              | nautobot_device_lifecycle_mgmt_hardwarelcm                       | UNIQUE          |
 | unique_inventory_item_part                                      | nautobot_device_lifecycle_mgmt_hardwarelcm                       | UNIQUE          |
 +-----------------------------------------------------------------+------------------------------------------------------------------+-----------------+
+102 rows in set (0.00 sec)
```
